# print('I %d savage' % 94)
# print('I %3d savage' % 94)
# print('I %03d savage' % 94)
# print('I {0:d} savage'.format (94))
# print('I {0:3d} savage'.format (94))
# print('I {0:03d} savage'.format (94))
# print('I %f savage' % 94)
# print('I %.2f savage' % 94)
# print('I {0:f} savage'.format (94))
# print('I {0:.2f} savage'.format (94))
# print('I %s savage' % '94')
# print('I {0:s} savage'.format (94))
# a = int(input('輸入您要的數值'))

# print('%d' % a)
# print('%5d'%a)
# print('%05d'%a)
# a = float(input('輸入您要的數值'))

# print('%f' % a)
# print('%.2f' % a)
# a = 5
# b = 5
# ans = eval('a+b')
# print(ans)
import datetime

# print(datetime.date.today())
# Date= datetime.date.today()
# print(Date)
# print(Date.year)
# print(Date.month)
# print(Date.day)
# Date= datetime.date.today()
# print(Date.strftime())
day = input('年/月/天')
print(day)
birth = datetime.datetime.strptime(day, '%Y/%m/%d')
print(birth.date())
print(birth.year)
print(birth.month)
print(birth.day)
